WovynTemperature/Models/TemperatureProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WovynTemperature.Models
{
	public class TemperatureProfile
	{
		public string Name { get; set; }
		public string Location { get; set; }
		public double ThresholdTemperature { get; set; }
		public string ToSMSNumber { get; set; }
		public string FromSMSNumber { get; set; }
	}
}

WovynTemperature/Models/TemperatureReading.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WovynTemperature.Models
{
	public class TemperatureReading
	{
		[JsonProperty(PropertyName = "id")]
		public int ID { get; set; }

		[JsonProperty(PropertyName = "temperature")]
		public double Temperature { get; set; }

		[JsonProperty(PropertyName = "timestamp")]
		public string TimeStamp { get; set; }

		[JsonIgnore]
		public bool IsTemperatureViolation { get; set; }
	}
}

WovynTemperature/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WovynTemperature.Utils;

namespace WovynTemperature.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			return View();
		}

		public ActionResult Contact()
		{
			return View();
		}
	}
}

WovynTemperature/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WovynTemperature.Models;
using WovynTemperature.Utils;

namespace WovynTemperature.Controllers
{
	public class ProfilesController : Controller
	{
		// GET: Profiles
		public ActionResult Index()
		{
			return View(TemperaturePicoInterface.GetTemperatureProfile());
		}

		[HttpGet]
		public ActionResult TemperatureProfile()
		{
			return PartialView("_Profile", TemperaturePicoInterface.GetTemperatureProfile());
		}

		// GET: Profiles/Edit/5
		public ActionResult Edit()
		{
			return View(TemperaturePicoInterface.GetTemperatureProfile());
		}

		// POST: Profiles/Edit/5
		[HttpPost]
		public ActionResult Edit(TemperatureProfile profile)
		{
			try
			{
				TemperaturePicoInterface.SetTemperatureProfile(profile);
				return RedirectToAction("Index");
			}
			catch
			{
				return View(profile);
			}
		}
	}
}

WovynTemperature/Controllers/ReadingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WovynTemperature.Utils;

namespace WovynTemperature.Controllers
{
	public class ReadingsController : Controller
	{
		// GET: Readings
		public ActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public ActionResult Readings()
		{
			var temperatureReadings = TemperaturePicoInterface.GetTemperatureReadings();
			temperatureReadings.Reverse();
			var temperatureViolationReadings = TemperaturePicoInterface.GetTemperatureViolationReadings();
			TemperaturePicoInterface.MarkTemperatureViolations(temperatureReadings, temperatureViolationReadings);
			return PartialView("_Readings", temperatureReadings);
		}
	}
}

WovynTemperature/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<p>This site provides information about the temperature readings generated by the wovyn sensor.</p>

WovynTemperature/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

@*<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@

WovynTemperature/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Wovyn Temperatures";
}

WovynTemperature/Views/Profiles/Edit.cshtml
@model WovynTemperature.Models.TemperatureProfile

@{
    ViewBag.Title = "Edit Profile";
}

<h2>Edit Profile</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TemperatureProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThresholdTemperature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThresholdTemperature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThresholdTemperature, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToSMSNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToSMSNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToSMSNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromSMSNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromSMSNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromSMSNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WovynTemperature/Views/Profiles/Index.cshtml
@model WovynTemperature.Models.TemperatureProfile

@{
	ViewBag.Title = "View Profile";
}
<div id="profile-container"></div>

@section scripts {
	<script>
		$(document).ready(function () {
			setInterval(updateReadings, 1000)
		});

		function updateReadings() {
			$.ajax({
				url: "/Profiles/TemperatureProfile",
				type: "GET",
			}).done(function (partialViewResult) {
				document.getElementById('profile-container').innerHTML = partialViewResult;
			});
		}
	</script>
}

WovynTemperature/Views/Profiles/_Profile.cshtml
@model WovynTemperature.Models.TemperatureProfile

<h2>View Profile</h2>

<div>
    <h4>TemperatureProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThresholdTemperature)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThresholdTemperature)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToSMSNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToSMSNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FromSMSNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromSMSNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ })
</p>

WovynTemperature/Views/Readings/Index.cshtml
@model List<WovynTemperature.Models.TemperatureReading>

@{
	ViewBag.Title = "Wovyn Temperatures";
}

<div id="readings-container"></div>

@section scripts {
	<script>
		$(document).ready(function () {
			setInterval(updateReadings, 1000)
		});

		function updateReadings() {
			$.ajax({
				url: "/Readings/Readings",
				type: "GET",
			}).done(function (partialViewResult) {
				document.getElementById('readings-container').innerHTML = partialViewResult;
			});
		}
	</script>
}

WovynTemperature/Views/Readings/_Readings.cshtml
@model List<WovynTemperature.Models.TemperatureReading>

<div class="row">
	<div class="col-md-12">
		<h2>Current Temperature</h2>
		<p>&nbsp;</p>
		@if (Model.Count() != 0)
		{
			var item = Model.First();
			Model.RemoveAt(0);
			if (item.IsTemperatureViolation)
			{
				<h3 class="temperature-violation">Temperature Violation</h3>
			}
			<dl class="dl-horizontal">
				<dt>
					@Html.LabelFor(modelItem => item.ID)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.ID)
				</dd>

				<dt>
					@Html.LabelFor(modelItem => item.Temperature)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.Temperature)
				</dd>

				<dt>
					@Html.LabelFor(modelItem => item.TimeStamp)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.TimeStamp)
				</dd>
			</dl>
		}
		else
		{
			<h3 class="information">No temperature readings</h3>
		}
	</div>
	<div class="col-md-12">
		<h2>Recente Temperature Readings</h2>
		<p>&nbsp;</p>
		@if (Model.Count() == 0)
		{
			<h3 class="information">No recent temperature readings</h3>
		}
		@foreach (var item in Model)
		{
			if (item.IsTemperatureViolation)
			{
				<h3 class="temperature-violation">Temperature Violation</h3>
			}
			<dl class="dl-horizontal">
				<dt>
					@Html.LabelFor(modelItem => item.ID)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.ID)
				</dd>

				<dt>
					@Html.LabelFor(modelItem => item.Temperature)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.Temperature)
				</dd>

				<dt>
					@Html.LabelFor(modelItem => item.TimeStamp)
				</dt>
				<dd>
					@Html.DisplayFor(modelItem => item.TimeStamp)
				</dd>
			</dl>
			<hr />
		}
	</div>
	<div class="col-md-12">
	</div>
</div>

WovynTemperature/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Wovyn Temperature Readings", "Index", "Readings", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Temperature Readings", "Index", "Readings")</li>
					<li>@Html.ActionLink("Temperature Profile", "Index", "Profiles")</li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Wovyn Temperature</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>